name: surl
version: 0.7
summary: Ubuntu Store API thin wrapper.
description: |
  Utility for easying authorization for the Ubuntu Store API.
confinement: strict
grade: stable

apps:
  surl:
    command: usr/bin/python3 -u $SNAP/bin/surl_cli.py
    plugs: [network-bind, network]
  metrics:
    command: usr/bin/python3 -u $SNAP/bin/surl_metrics.py
    plugs: [network-bind, network]
  storeops:
    command: usr/bin/python3 -u $SNAP/bin/surl_storeops.py
    plugs: [network-bind, network]

parts:
  surl:
    plugin: python
    source: .
    build-packages:
      - libffi-dev
    stage-packages:
      - libsodium18
      - libsodium-dev
    python-packages:
      - requests
      - pymacaroons
      - tabulate
    prime:
      - -install
