sudo: required
dist: trusty
language: python
python:
- '3.4'
script: python setup.py test
before_install:
- sudo add-apt-repository ppa:chris-lea/libsodium -y
- sudo apt update -qq
- sudo apt install -y libnacl-dev libsodium-dev libffi-dev
services:
- docker
after_success:
- openssl aes-256-cbc -K $encrypted_cee03c4e4c41_key -iv $encrypted_cee03c4e4c41_iv
  -in .travis_snapcraft.cfg -out .snapcraft.cfg -d
- if [ "$TRAVIS_BRANCH" = "master" ]; then
  docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c
  "apt update -qq && apt install snapcraft -y && cd $(pwd) &&
  mkdir -p ~/.config/snapcraft && cp .snapcraft.cfg ~/.config/snapcraft/snapcraft.cfg &&
  snapcraft && snapcraft push *.snap --release edge";
  fi
