language: python
python:
- '2.7'
- pypy

dist: xenial

addons:
  apt:
    packages:
    - python3-setuptools
    - libffi-dev
  snaps:
    - name: snapcraft
      confinement: classic
      channel: edge

script:
- python -m unittest tests

after_success:
- snapcraft snap

deploy:
  on:
    branch: master
  provider: snap
  snap: surl*.snap
  channel: edge
  skip_cleanup: true
