language: python
dist: xenial

python:
- '2.7'
- '3.5'
- 'pypy'
- 'pypy3.5'

script: python -m unittest tests

jobs:
  include:
  - stage: deploy
    python: 'pypy3.5'
    addons:
      apt:
        packages:
        - python3-setuptools
      snaps:
      - name: snapcraft
        confinement: classic
        channel: edge
    script: snapcraft snap
    deploy:
      provider: snap
      on:
        branch: master
      snap: surl*.snap
      channel: edge
      skip_cleanup: true
