name: surl
version: 0.2
summary: Ubuntu Store API thin wrapper.
description: |
  Utility for easying authorization for the Ubuntu Store API.
confinement: strict
grade: stable

apps:
  surl:
    command: usr/bin/python3 $SNAP/bin/surl.py
    plugs: [network-bind, network]

parts:
  surl:
    plugin: python3
    source: .
    stage-packages:
      - libsodium18
      - libsodium-dev
    python-packages:
      - requests
      - pymacaroons
    snap:
      - -install
