name: surl
summary: Ubuntu Store API thin wrapper.
adopt-info: surl
confinement: strict
grade: stable
base: core16

apps:
  surl:
    command: usr/bin/python3 -u $SNAP/bin/surl_cli.py
    plugs: [network-bind, network]
  metrics:
    command: usr/bin/python3 -u $SNAP/bin/surl_metrics.py
    plugs: [network-bind, network]
  storeops:
    command: usr/bin/python3 -u $SNAP/bin/surl_storeops.py
    plugs: [network-bind, network]
  monthinsnaps:
    command: usr/bin/python3 -u $SNAP/bin/surl_month_in_snaps.py
    plugs: [network-bind, network]

parts:
  surl:
    plugin: python
    source: .
    parse-info: [setup.py]
    requirements:
      - requirements.txt
    build-packages:
      - libffi-dev
    stage-packages:
      - libsodium18
      - libsodium-dev
    python-packages:
      - tabulate
      - iso8601
    prime:
      - -install
