name: Unit-Tests
on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install virtualenv
              run: sudo apt-get install python3-virtualenv
            - name: Run unit tests
              run: |
                 make test
    lint:
        name: black/lint
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: install virtualenv
              run: sudo apt-get install python3-virtualenv
            - name: Perform black/lint tests
              run: |
                 make lint
